### ISSUE TITLE
working with windows

### ISSUE THREAD

**Issue by tmontobbio** [learn-co-curriculum/phase-3-sql-select-and-update#5]
### Canvas Link

https://learning.flatironschool.com/courses/5215/pages/sql-insert-select-update-and-delete?module_item_id=469985

### Concern

Because of the nature of this lesson, creating a db file in the local folder (WSL root), and having the DB browser installed in the windows root;

-need to move file in and out of WSL VM
-in order to execute terminal commands like "sqlite3 pets_database.db < 01_insert_cats_into_cats_table.sql"
   will have to move db file back into WSL root.

is there any solution for this that I can utilize? or do I need to buy a mac haha

-thanks!

**Comment by lizbur10** [comment]
Hi @tmontobbio! I'm so sorry about the inconvenience! The curriculum team monitors these issues so that we can fix typos and bugs in the curriculum, but we aren't equipped to provide support with environment or platform issues.

To get help with your question, you should either reach out to your instructor or use the
[Pair with a TC](https://docs.google.com/document/d/1Gko5UFzCBhpo1R0V_Tx2JHSK9cRC2b_53Ky3u5Qtzlk/edit) feature in Canvas to connect with a Technical Coach on the Academic Success Team

Hope you are able to get this resolved!
