### ISSUE TITLE
Multiple lessons need a fork button instead of a text link to fork for consistency

### ISSUE THREAD

**Issue by Pete-Fowler** [learn-co-curriculum/phase-3-sql-select-and-update#6]
### Canvas Link

https://learning.flatironschool.com/courses/5222/pages/sql-insert-select-update-and-delete?module_item_id=479803

### Concern

This is one of several lessons missing the Fork button at the top of the canvas page next to the GitHub link, and instead it has a text link to fork the repo. 

### Suggested Changes

Consistency in the UI and content across lessons can be improved by adding the button to the top and removing the text link to match all the other lessons.  If you can point me to the correct repo for the structure of the page or canvas, I could try to fix this and submit some PRs, but the actual structure / components of the page do not exist in these curriculum repos and I can't see them anywhere. 🚀🚀🚀

**Comment by lizbur10** [comment]
Hi @Pete-Fowler! This lesson doesn't have a fork button because it is a code-along rather than a lab - the fork button is added automatically to any lessons that include test files. Because code-alongs generally don't, the fork button doesn't appear. Unfortunately, there currently isn't a good way to differentiate lessons from code-alongs, but hopefully we will be able to fix this at some point moving forward. 

I'm going to go ahead and close this issue, but please let us know if you see any labs with tests that don't have a fork button. 

Thanks for contributing to the Flatiron School curriculum 💙
